use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=APP_VERSION");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo"));
    let version = env::var("APP_VERSION").unwrap_or_else(|_| "dev".to_owned());
    let code = format!(
        "/// Build-time version generated by build.rs.\npub const APP_VERSION: &str = {version:?};\n"
    );
    fs::write(out_dir.join("generated.rs"), code).expect("write generated.rs");
}
